### PR TITLE
feat: add custom dialog option

### LINKED ISSUE #116: How do I change the update message?
I'd like to customize the dialog message when user downloaded the update. Is it possible?

### PR DESCRIPTION
**Pull request by ArthurLobopro**
Hello, how you merged the PR #105 I rewrite the PR #97 to avoid merge conflicts. I am unable to test the feature on windows or macos so if someone can test it I will be grateful :)

Closes #116

### CODE REVIEW

**Review by erikian — APPROVED** [review]

**Review by dsanders11 — DISMISSED** [review]
Needs semicolons to match coding style.

**Comment by ArthurLobopro** [comment]
I think I added all the missing semicolons, did I forget someone?

**Review by erickzhao — COMMENTED** [review]
Some general feedback on the approach:

@ArthurLobopro have you considered instead exposing an API that allows users to hook in their own custom dialog code?

I wonder if a more generalized approach would be better than adding individual API options for the individual buttons.

**Comment by ArthurLobopro** [comment]
@erickzhao I think the most people that want to change something on the dialog only wants to change the update message to something different (Like the Issue #116 ) or in another language (this is my case). 

Somehow, a way to do my own custom dialog can be interesting I think. How would you implements that?

**Comment by dsanders11** [comment]
I think the possibility to localize the text is a reasonable feature, and should probably be supported without requiring users to re-implement the dialog all together.

For customizing the dialog more deeply, though, we could look at providing a hook, say `IUpdateElectronAppOptions .onNotifyUser` which takes a function. Then we could export a `makeUserNotifier(options: IDialogMessages)`, which has this code moved to it and returns a function.

https://github.com/electron/update-electron-app/blob/06373904910b96aebd72f31434f81d0184693906/src/index.ts#L186-L202

Then to do localization the user would do:

```js
updateElectronApp({
  ...,
  onNotifyUser: makeUserNotifier({ 
    restartButtonText: 'Restart!!'
  })
})
```

And if they wanted to more deeply customize the notify they have a hook to do whatever they'd like:

```js
updateElectronApp({
  ...,
  onNotifyUser: (event, releaseNotes, releaseName, releaseDate, updateURL) => {
    if (releaseName === 'AwesomeRelease') {
      // Do fireworks
    }
  }
})
```

**Comment by ArthurLobopro** [comment]
@dsanders11 great idea! @erickzhao what do you think about that?

**Comment by ArthurLobopro** [comment]
I realize if we provide the hook we will lose the logger context, because the logger is declared inside the `updateElectronApp` function.

https://github.com/electron/update-electron-app/blob/06373904910b96aebd72f31434f81d0184693906/src/index.ts#L154-L156

To solve it I think we can add a listener just to log it: 

```ts
 autoUpdater.on(
      'update-downloaded',
      (event, releaseNotes, releaseName, releaseDate, updateURL) => {
        log('update-downloaded', [event, releaseNotes, releaseName, releaseDate, updateURL]);
      },
    );
    
 autoUpdater.on(
  'update-downloaded',
  (event, releaseNotes, releaseName, releaseDate, updateURL) => { 
      const { title, restartButtonText, laterButtonText, detail } = opts.dialog;

      const dialogOpts = {
        type: 'info',
        buttons: [restartButtonText, laterButtonText],
        title,
        message: process.platform === 'win32' ? releaseNotes : releaseName,
        detail,
     };

    dialog.showMessageBox(dialogOpts).then(({ response }) => {
        if (response === 0) autoUpdater.quitAndInstall();
    });
  },);
```

**Comment by ArthurLobopro** [comment]
I found another thing.

When we create the dialog, we pick the dialog API from electron in the options

https://github.com/electron/update-electron-app/blob/06373904910b96aebd72f31434f81d0184693906/src/index.ts#L124

https://github.com/electron/update-electron-app/blob/06373904910b96aebd72f31434f81d0184693906/src/index.ts#L132 

But to create a separated function to create the notifier, maybe we will need to import directly from electron.

**Comment by dsanders11** [comment]
> When we create the dialog, we pick the dialog API from electron in the options

It looks like this is just an undocumented option for testing purposes (I'm not familiar with this code base, but that's my take from a quick read), so it could similarly be an undocumented option on `IDialogMessages`, or we could tweak the signature of the proposed `onNotifyUser` to receive an object and it could be an undocumented value there:

```js
updateElectronApp({
  ...,
  onNotifyUser: (info) => {
    const { event, releaseNotes, releaseName, releaseDate, updateURL } = info;
    // info.electron is an undocumented value for tests
    if (releaseName === 'AwesomeRelease') {
      // Do fireworks
    }
  }
})
```

**Comment by ArthurLobopro** [comment]
I don't know why this error happens. The Electron namespace is already referenced here:

https://github.com/electron/update-electron-app/blob/1c9e970c0785f25b9d6528eae0dcd35204c8c08d/src/index.ts#L207

**Comment by ArthurLobopro** [comment]
Can someone test it on Windows or Macos? I am using Linux on my PC.

**Comment by ArthurLobopro** [comment]
Do we had any progress here?

**Comment by doctorXWrites** [comment]
Any update here? I'm looking for some way to be able to show release notes in update dialog.

**Comment by ArthurLobopro** [comment]
@doctorXWrites  Just waiting for approval, but maybe the reviewer forgot this PR because Github stops showing PRs with no activity after 2 weeks. 

I will mark he here to confirm this

@dsanders11

**Review by erickzhao — DISMISSED** [review]
I have a few things to change that I'm planning on pushing up. Sorry for the wait @ArthurLobopro!

**Comment by ArthurLobopro** [comment]
@erickzhao No problem, I'm available to help if necessary

**Comment by erickzhao** [comment]
Here's a pre-requisite PR that makes the testing experience more delightful: https://github.com/electron/update-electron-app/pull/171

I have my implementation changes ready at the moment locally but wanted to improve test coverage when landing a new features.

**Comment by erickzhao** [comment]
Okay, all PRs have been merged, will write tests for my implementation changes and request reviews from other maintainers.

**Comment by erickzhao** [comment]
Hey @ArthurLobopro, I just pushed up all changes and rebased against `main`.

The biggest difference is that the default implementation for `makeUserNotifier` is used if `notifyUser` is true but no `onNotifyUser` function is passed through. I also added tests for `makeUserNotifier`.

Do you mind giving this a spin to test it out?

**Review by erikian — APPROVED** [review]
Looking good! :shipit:

**Review by dsanders11 — APPROVED** [review]

**Review by erickzhao — APPROVED** [review]

**Pull request merged**
