### PR TITLE
feat: add `logger` option

### LINKED ISSUE #4: log in the renderer process
The current recommendation is to call `require('update-electron-app')({repo: 'some/repo'}) from the main process, but calls to `console.log` from a packaged app will just go into the ether.

Maybe something [electron-log](https://ghub.io/electron-log) would be a good fit for this.

### PR DESCRIPTION
**Pull request by zeke**
Resolves #4

### CODE REVIEW

**Comment by zeke** [comment]
Gonna refactor to accept a logger, per feedback in #4

**Comment by zeke** [comment]
This is ready for another look, @juliangruber and @MarshallOfSound 

Kinda feel like `electron-log` should be the default instead of `console`, as `console.log` just whispers into the ether on a packaged app, right?

**Comment by MarshallOfSound** [comment]
> Kinda feel like electron-log should be the default 

I think we should let users make that choice, I don't want to add even more stuff to the dep tree that users probably won't use as most people already have their own logging solutions.

**Pull request merged**
