### PR TITLE
feat: add User-Agent request header

### LINKED ISSUE #14: Add machine-id to query
https://github.com/automation-stack/node-machine-id

### PR DESCRIPTION
**Pull request by zeke**
This is a way to resolve #14 that doesn't include user-specific data.

Trying to adhere to [official User-Agent syntax](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent):

```
User-Agent: <product> / <product-version> <comment>

Common format for web browsers:

User-Agent: Mozilla/<version> (<system-information>) <platform> (<platform-details>) <extensions>
```

The string should look something like

```
update-electron-app/1.1.0 (darwin: x64)
```

### CODE REVIEW

**Comment by juliangruber** [comment]
Actually, we should already know all this from their request url:

```js
update.electron.org/electron/update-electron-app/darwin/1.1.0
```

Not sure if this is adding any info...

**Comment by zeke** [comment]
> This will only take affect on macOS, on windows their is no option to set headers

Nooo! 😢Sad.

> we should already know all this from their request url:

True, URL does tell us the platform. But the `version` in the URL is the version of the app, whereas the `version` in the user agent is the version of the `update-electron-app` module that's making the request. I think it's also still useful because it will enable us to distinguish `update-electron-app` traffic from the rest.

**Comment by zeke** [comment]
@MarshallOfSound do you know if a query param will make it through intact?

**Comment by zeke** [comment]
This doesn't solve all our data collection goals, but it's a step. Gonna go ahead and ship it.

**Pull request merged**
