### PR TITLE
feat: custom dialog

### PR DESCRIPTION
**Pull request by ArthurLobopro**
Hi, I've added a custom text to notify dialog. That can help users from other countries that wish only to switch language of buttons or other small changes to the text.

### CODE REVIEW

**Review by BlackHole1 — APPROVED** [review]
LGTM

**Comment by ArthurLobopro** [comment]
someone here?

**Review by erickzhao — CHANGES_REQUESTED** [review]
There are a lot of unnecessary formatting changes in the `index.d.ts` that should be cleaned up.

There's a PR open that converts this module to TS though so this should maybe land after #105

**Comment by ArthurLobopro** [comment]
Oh, sorry. My vscode was set to remove semicolons.

**Comment by jordanamr** [comment]
Hello, any news on merging that PR ? :)

**Comment by ArthurLobopro** [comment]
Apparently no.

**Comment by erikian** [comment]
Superseded by #126

**Pull request closed without merging**
